# Generated by Django 6.0.4 on 2026-06-09 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_registration'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='registration',
            name='employees_r_status_1ea31b_idx',
        ),
        migrations.RemoveIndex(
            model_name='registration',
            name='employees_r_usernam_4a66ed_idx',
        ),
        migrations.RemoveIndex(
            model_name='registration',
            name='employees_r_email_1a0b51_idx',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
