# Generated by Django 6.0.4 on 2026-06-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_registration_employees_r_status_1ea31b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, default='Employee', help_text='Job position/designation', max_length=100, null=True),
        ),
    ]
