# Generated by Django 6.0.4 on 2026-06-14 10:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_no', models.CharField(blank=True, help_text='Enter a NID, passport, birth certificate, or other identification number.', max_length=100, validators=[django.core.validators.RegexValidator(message='Enter a valid NID, passport, birth certificate, or other identification number.', regex='^[A-Za-z0-9][A-Za-z0-9\\-/\\s]*$')], verbose_name='Identification number')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='employee_profiles/pictures/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('nationality', models.CharField(blank=True, max_length=80)),
                ('present_address', models.TextField(blank=True)),
                ('permanent_address', models.TextField(blank=True)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid emergency contact number (10-15 characters).', regex='^[0-9+\\-\\s()]{10,15}$')])),
                ('emergency_contact_name', models.CharField(blank=True, max_length=120)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=80)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended_profile', to='employees.employee')),
            ],
        ),
    ]
