# Generated by Django 6.0.4 on 2026-06-15 09:26

import django.db.models.deletion
import django.db.models.functions.text
import employees.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_alter_department_name'),
        ('employees', '0005_empprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_id', models.CharField(default=employees.models.generate_designation_id, editable=False, max_length=12, unique=True)),
                ('designation_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employee_designations', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designations', to='departments.department')),
            ],
            options={
                'verbose_name': 'Employee Designation',
                'verbose_name_plural': 'Employee Designations',
                'ordering': ['designation_name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('designation_name'), name='unique_emp_designation_name_ci')],
            },
        ),
    ]
