# Generated by Django 6.0.4 on 2026-06-15 09:55

from django.db import migrations, models


def normalize_employee_ids(apps, schema_editor):
    Employee = apps.get_model('employees', 'Employee')
    employees = list(Employee.objects.order_by('pk'))
    if len(employees) > 9999:
        raise RuntimeError('Employee ID generation supports at most 9999 employees.')

    for employee in employees:
        Employee.objects.filter(pk=employee.pk).update(
            employee_id=f'TEMP{employee.pk:016d}',
        )

    for number, employee in enumerate(employees, start=1):
        Employee.objects.filter(pk=employee.pk).update(
            employee_id=f'EMP{number:04d}',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_employee_designation'),
    ]

    operations = [
        migrations.RunPython(
            normalize_employee_ids,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(db_index=True, editable=False, max_length=7, unique=True),
        ),
    ]
