# Generated by Django 6.0.4 on 2026-06-20 12:25

from django.db import migrations, models


def normalize_leave_type_names(apps, schema_editor):
    LeaveType = apps.get_model('employees', 'LeaveType')
    valid_names = {
        'Casual Leave',
        'Sick Leave',
        'Earned Leave',
        'Other',
    }
    LeaveType.objects.filter(name__isnull=True).update(name='Casual Leave')
    LeaveType.objects.exclude(name__in=valid_names).update(name='Casual Leave')


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_alter_employee_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetype',
            name='description',
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(choices=[('Casual Leave', 'Casual Leave'), ('Sick Leave', 'Sick Leave'), ('Earned Leave', 'Earned Leave'), ('Other', 'Other')], default='Casual Leave', max_length=50),
        ),
        migrations.RunPython(normalize_leave_type_names, migrations.RunPython.noop),
    ]
