# Generated by Django 6.0.4 on 2026-06-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_remove_leavetype_description_alter_leavetype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='custom_leave',
            field=models.PositiveIntegerField(blank=True, help_text='Admin-defined total leave balance for this employee. If set, leave type balances will be ignored.', null=True),
        ),
    ]
