# Generated by Django 6.0.4 on 2026-06-27 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_employee_custom_leave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empprofile',
            old_name='bio',
            new_name='job_description',
        ),
        migrations.AddField(
            model_name='empprofile',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='empprofile',
            name='service_length',
            field=models.CharField(blank=True, help_text='For example: 3 years 6 months.', max_length=100),
        ),
        migrations.AlterField(
            model_name='empprofile',
            name='identification_no',
            field=models.CharField(blank=True, help_text='Enter a NID, passport, birth certificate, or other identification number.', max_length=100, validators=[django.core.validators.RegexValidator(message='Enter a valid NID, passport, birth certificate, or other identification number.', regex='^[A-Za-z0-9][A-Za-z0-9\\-/\\s]*$')], verbose_name='Identification No'),
        ),
    ]
