# Generated by Django 6.0.4 on 2026-06-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_rename_bio_empprofile_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empprofile',
            name='service_length',
        ),
        migrations.AlterField(
            model_name='empprofile',
            name='education',
            field=models.TextField(),
        ),
    ]
