# Generated by Django 6.0.4 on 2026-06-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_empsalary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empsalary',
            name='bank_account_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='empsalary',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='empsalary',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
