# Generated by Django 6.0.4 on 2026-06-27 16:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_alter_empsalary_bank_account_no_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empsalary',
            name='increment_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='empsalary',
            name='last_increment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empsalary',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_salary_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
