# Generated by Django 6.0.4 on 2026-05-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_employee_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='dept_name',
            field=models.CharField(blank=True, choices=[('MEDICINE', 'Medicine'), ('NON_MEDICINE', 'Non-Medicine')], max_length=100, null=True),
        ),
    ]
