# Generated by Django 6.0.4 on 2026-05-25 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_registration_dept_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='dept_name',
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('SELECT', 'Select'), ('MEDICINE', 'Medicine'), ('GROCERY', 'Grocery'), ('ACCOUNTS', 'Accounts'), ('CASH', 'Cash')], default='SELECT', max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department'),
        ),
    ]
