# Generated by Django 6.0.4 on 2026-05-25 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_registration_dept_name_alter_department_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='registration',
            name='accounts_re_status_f0eb59_idx',
        ),
        migrations.RemoveIndex(
            model_name='registration',
            name='accounts_re_usernam_829080_idx',
        ),
        migrations.RemoveIndex(
            model_name='registration',
            name='accounts_re_email_563cb3_idx',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
