# Generated by Django 6.0.4 on 2026-06-06 04:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_employee_emergency_contact_employee_email_and_more'),
        ('departments', '0002_alter_department_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.AlterField(
            model_name='registration',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department'),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='registration',
            name='accounts_re_status_f0eb59_idx',
        ),
        migrations.RemoveIndex(
            model_name='registration',
            name='accounts_re_usernam_829080_idx',
        ),
        migrations.RemoveIndex(
            model_name='registration',
            name='accounts_re_email_563cb3_idx',
        ),
        migrations.AlterField(
            model_name='registration',
            name='designation',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be 10-15 digits.', regex='^[0-9+\\-\\s()]{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='registration',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin/HR'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=10),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
