# Generated by Django 6.0.4 on 2026-06-06 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LAF', '0004_leaverequest_approved_by_leaverequest_leave_type_and_more'),
        ('accounts', '0008_remove_employee_department_and_more'),
        ('attendances', '0002_alter_attendance_employee'),
        ('departments', '0003_alter_department_manager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='updated_at',
        ),
    ]
