# Generated by Django 6.0.4 on 2026-06-06 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_employee_remove_registration_approved_at_and_more'),
        ('departments', '0003_alter_department_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_registrations', to='departments.department'),
        ),
    ]
