from django.urls import path
from . import views

urlpatterns = [
    path('', views.DashboardView.as_view(), name='emp_dashboard'),
    path('leave/apply/', views.LeaveApplyView.as_view(), name='leave_apply'),
    path('leave/history/', views.LeaveHistoryView.as_view(), name='leave_history'),
    path('leave/detail/<int:pk>/', views.LeaveDetailView.as_view(), name='leave_detail'),
    path('profile/', views.EmployeeProfileView.as_view(), name='employee_profile'),
    path('profile/edit/', views.EmployeeProfileUpdateView.as_view(), name='employee_profile_edit'),
    path('profile/picture/upload/', views.profile_picture_upload, name='profile_picture_upload'),
    path('leave/cancel/<int:pk>/', views.leave_cancel, name='leave_cancel'),
    path('leave/approve/<int:pk>/', views.leave_approve, name='leave_approve'),
    path('leave/reject/<int:pk>/', views.leave_reject, name='leave_reject'),
    path('leave-types/', views.LeaveTypeListView.as_view(), name='leave_type_list'),
    path('leave-types/add/', views.LeaveTypeCreateView.as_view(), name='leave_type_add'),
    path('leave-types/<int:pk>/edit/', views.LeaveTypeUpdateView.as_view(), name='leave_type_edit'),
    path('leave-types/<int:pk>/delete/', views.LeaveTypeDeleteView.as_view(), name='leave_type_delete'),
    path('setup/departments/', views.DepartmentListView.as_view(), name='department_list'),
    path('setup/departments/add/', views.DepartmentCreateView.as_view(), name='department_add'),
    path('setup/departments/<int:pk>/edit/', views.DepartmentUpdateView.as_view(), name='department_edit'),
    path('setup/departments/<int:pk>/delete/', views.DepartmentDeleteView.as_view(), name='department_delete'),
    path('setup/designations/', views.DesignationListView.as_view(), name='designation_list'),
    path('setup/designations/add/', views.DesignationCreateView.as_view(), name='designation_add'),
    path('setup/designations/<int:pk>/edit/', views.DesignationUpdateView.as_view(), name='designation_edit'),
    path('setup/designations/<int:pk>/delete/', views.DesignationDeleteView.as_view(), name='designation_delete'),
    path('employees/', views.EmployeeListView.as_view(), name='employee_list'),
    path('employees/<int:pk>/', views.EmployeeDetailView.as_view(), name='employee_detail'),
    path('employees/<int:pk>/edit/', views.employee_admin_edit, name='employee_admin_edit'),
    path('employees/<int:pk>/update/', views.employee_admin_update, name='employee_admin_update'),
    path('employees/departments/quick-create/', views.department_quick_create, name='department_quick_create'),
]
