# Generated by Django 6.0.4 on 2026-06-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAF', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('total_days', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Admin remarks/comments', null=True)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.RemoveField(
            model_name='leave',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='leave_type',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='total_days',
        ),
        migrations.AddField(
            model_name='leavetype',
            name='yearly_limit',
            field=models.PositiveIntegerField(default=0, help_text='Maximum days allowed per year'),
        ),
    ]
