# Generated by Django 6.0.4 on 2026-06-06 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAF', '0003_leaverequest_remove_leave_approved_by_and_more'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laf_approved_requests', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LAF.leavetype'),
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
