# Generated by Django 6.0.4 on 2026-06-09 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LAF', '0004_leaverequest_approved_by_leaverequest_leave_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
        migrations.DeleteModel(
            name='LeaveType',
        ),
    ]
