# Generated by Django 6.0.4 on 2026-06-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_alter_department_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('MEDICINE', 'Medicine'), ('NON-MEDICINE', 'Non-Medicine')], max_length=100, unique=True),
        ),
    ]
