# Generated by Django 6.0.4 on 2026-06-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('MEDICINE', 'Medicine'), ('NON-MEDICINE', 'Non-Medicine'), ('ACCOUNTS', 'Accounts')], max_length=100, unique=True),
        ),
    ]
